apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeployment
  # namespace: devproject
spec:
  replicas: 1
  selector:
    matchLabels:
      apptype: web
      env: dev
  template:
    metadata:
      name: webtemp
      labels:
        apptype: web
        env: dev
    spec:
      containers:
      - image: shivapraveendocker/blugoonweb:v1
        name: webcon
        imagePullPolicy: Always
        ports:
        -  name: apache
           containerPort: 80
           protocol: TCP
        resources:
           requests:
             memory: "20Mi"
             cpu: "20m"
           limits:
             memory: "30Mi"
             cpu: "40m"
---
apiVersion: v1
kind: Service
metadata:
 name: websvc   #service name (it can be any name)
#  namespace: devproject
spec:
 type: NodePort
 ports:
 - name: apache
   nodePort: 30002
   port: 80 #service port
   targetPort: 80 #container port
   protocol: TCP
 selector:     #mapping to pod
   apptype: web
   env: dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: webingress
  #  namespace: devproject
spec:
   ingressClassName: nginx
   rules:
   - host: "shivatech.in.net"
     http:
       paths:
       - path: "/"
         pathType: "Prefix"
         backend:
           service:
             name: websvc
             port:
              number: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: webhpa
  #  namespace: devproject
spec:
  maxReplicas: 10
  minReplicas: 1
  targetCPUUtilizationPercentage: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webdeployment
