apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
spec:
  containers:
  - name: alpine
    image: alpine
    args:
    - sleep
    - "100000000"

# exec into the pod traffic-generator
# kubectl exec -it traffic-generator -- sh
# apk add wrk
# wrk -c 5 -t 5 -d 300s -H "Connection: Close" http://shivatech.in.net/