apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
   name: webvpa
  #  namespace: devproject
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webdeployment
  updatePolicy:
    updateMode: "Auto"